{
  parserClass="com.forgerock.parser.OpenAMLogParser"

extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

psiClassPrefix="OpenAMLog"
psiImplClassSuffix="Impl"
psiPackage="com.forgerock.psi"
psiImplPackage="org.forgerock.openam.logreader.psi.impl"

elementTypeHolderClass="org.forgerock.openam.logreader.psi.OpenAMLogTypes"
elementTypeClass="org.forgerock.openam.logreader.psi.OpenAMLogElementType"
tokenTypeClass="org.forgerock.openam.logreader.psi.OpenAMLogTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY